name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc

    steps:
    - uses: actions/checkout@v3

    - name: Set up C++ compiler
      if: matrix.os != 'windows-latest'
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          sudo apt-get update
          sudo apt-get install -y g++-11
          echo "CXX=g++-11" >> $GITHUB_ENV
        else
          sudo apt-get update
          sudo apt-get install -y clang-12
          echo "CXX=clang++-12" >> $GITHUB_ENV
        fi

    - name: Set up MSVC on Windows
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run executable
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ./build/bin/Release/Battleship.exe
        else
          ./build/bin/Battleship
        fi 